### ISSUE TITLE
New admin fields

### ISSUE THREAD

**Issue by paulHempel** [CodeDesignInitiative/integrated-learning-environment#19]
- [x] Image per chat step
- [x] explanation for mission
- [x] hint for mission (shown on error)
- [ ] toggle: block or text editor

**Comment by chrbinder** [comment]
same as https://github.com/CodeDesignInitiative/integrated-learning-environment/issues/36
?

**Comment by paulHempel** [comment]
Basically. You declared the missing text-editor as bug, but it just wasn't implemented yet (fully). 

But we can close this issue and use #36 as reference as everything else here is done.
