### ISSUE TITLE
Setting the level of difficulty

### ISSUE THREAD

**Issue by MarvvanPal** [CodeDesignInitiative/integrated-learning-environment#29]
Depending on the set difficulty level, the e.g. complexity does not change. For example, the "Difficult" level is the easiest on "Level 1: Intro".

**Comment by paulHempel** [comment]
Don't understand. On the story page you can choose your difficulty, which is influenced by the set content. I don't see a technical bug 🤔

**Comment by MarvvanPal** [comment]
Tested it again - Bug seems to be fixed. Ticket closed.
