### ISSUE TITLE
Drag And Drop Editor

### ISSUE THREAD

**Issue by paulHempel** [CodeDesignInitiative/integrated-learning-environment#3]
JS Library:
http://sortablejs.github.io/Sortable/#shared-lists

Compare to DuoLingo word dragging in lections

**Comment by lambdaschmied2** [comment]
Initial version done. Closing this issue, create new ones based on feedback for specific features/bugs.

**Comment by paulHempel** [comment]
Initial version done. Closing this issue, create new ones based on feedback for specific features/bugs.
