### ISSUE TITLE
Images cannot be displayed in explanation screen in story levels

### ISSUE THREAD

**Issue by chrbinder** [CodeDesignInitiative/integrated-learning-environment#33]
When using the image syntax from the admin panel for story messages in the explanation field in the admin panel, the image is not displayed in the explanation screen in story levels

**Comment by paulHempel** [comment]
And it shouldn't in my opinion. The explanation text should be short and precise. I don't see a use for images. 
They would take up to much space. If you want to refer to the images you see in the chat, it may be better to refer to opening the tablet again

**Comment by paulHempel** [comment]
We may talk about if we want this feature in a future meeting. But I'll leave this as 'not planned'
