### ISSUE TITLE
rearranging css blocks doesn't update css

### ISSUE THREAD

**Issue by chrbinder** [CodeDesignInitiative/integrated-learning-environment#37]
In CSS story levels, dragging and/or rearranging CSS blocks doesn't update the page preview

**Comment by paulHempel** [comment]
Can't reproduce. Do we have a story mission with CSS yet?
When and where did this happen?

**Comment by paulHempel** [comment]
@chrbinder you have to add a $$placeholder$$ string if you set the "hidden css". Else the script doesn't know where to place the css from the user. Maybe it is missing in a certain mission (you set it in the "Rahmendesign" Mission and it already works)

**Comment by paulHempel** [comment]
Please reopen the issue if you can reproduce the issue even with a placeholder set
