### ISSUE TITLE
Hidden CSS is added to body-tag for CSS story levels and should be overwritable

### ISSUE THREAD

**Issue by chrbinder** [CodeDesignInitiative/integrated-learning-environment#38]
When selecting CSS as mission type for a story level, the page preview seems to inherit a standard CSS body rule with white background and sans-serif typefont regardless of what is written in the "hidden css" field in the admin panel.

Inheritance should either available to be selected additionally to custom css or be left out.

**Comment by paulHempel** [comment]
Can't reproduce. Fixed a small bug when changing difficulties, but CSS is always properly added.
Maybe fixed through #36
